version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/zinclabs

  build:
    commands:
      - pwd
      # - GIT_TAG="$(git describe --tags --abbrev=0)"
      # - GIT_HASH="$(git rev-parse --short HEAD)"
      - VERSION=v0.0.1

      - docker build -t cross-rs/x86_64-pc-windows-gnu:$VERSION -f Dockerfile.cross.x86_64-pc-windows-gnu .
      - docker tag cross-rs/x86_64-pc-windows-gnu:$VERSION public.ecr.aws/zinclabs/cross-rs/x86_64-pc-windows-gnu:$VERSION
      - docker push public.ecr.aws/zinclabs/cross-rs/x86_64-pc-windows-gnu:$VERSION
      