version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/zinclabs

  build:
    commands:
      - pwd
      # - GIT_TAG="$(git describe --tags --abbrev=0)"
      # - GIT_HASH="$(git rev-parse --short HEAD)"
      - docker build -t cross-rs-x86_64-unknown-linux-gnu:v0.0.1 -f Dockerfile.cross.x86_64-unknown-linux-gnu .
      - docker tag cross-rs-x86_64-unknown-linux-gnu:v0.0.1 public.ecr.aws/zinclabs/cross-rs-x86_64-unknown-linux-gnu:v0.0.1
      - docker push public.ecr.aws/zinclabs/cross-rs-x86_64-unknown-linux-gnu:v0.0.1
      # - 
      # - docker build -t cross-rs-x86_64-unknown-linux-gnu:latest -f Dockerfile.cross.x86_64-unknown-linux-gnu .
      # - docker tag cross-rs-x86_64-unknown-linux-gnu:latest public.ecr.aws/zinclabs/cross-rs-x86_64-unknown-linux-gnu:latest
      # - docker push public.ecr.aws/zinclabs/cross-rs-x86_64-unknown-linux-gnu:latest
      
