FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:latest

RUN dpkg --add-architecture arm64 && \
  apt-get update && \
  apt-get install --assume-yes wget unzip
RUN apt-get install --assume-yes openssl:arm64 libssl-dev:arm64

# Install protoc
RUN wget https://github.com/protocolbuffers/protobuf/releases/download/v22.0-rc2/protoc-22.0-rc-2-linux-aarch_64.zip
RUN unzip protoc-22.0-rc-2-linux-aarch_64.zip -d protoc
RUN cp protoc/bin/protoc /usr/local/bin/
RUN cp -r protoc/include/google /usr/local/include/
ENV OPENSSL_DIR=/usr/lib/ssl
